export const THEME = {
  colors: {
    background: '#F9F9F6',
    primaryOrange: '#F57C2A',
    primaryOrangeHover: '#E06B1D',
    primaryOrangeLight: '#FFF4EC',
    deepTeal: '#0E5B66',
    deepTealLight: '#E8F4F6',
    deepTealDark: '#083B43',
    darkNavy: '#0E1726',
    cardWhite: '#FFFFFF',
    border: '#EAEAEA',
    borderLight: '#F0F0EE',
    textPrimary: '#0E1726',
    textSecondary: '#5A6578',
    textMuted: '#8E9AA8',
    successGreen: '#10B981',
    successGreenLight: '#ECFDF5',
    unswYellow: '#FFE500',
    grayButton: '#F0F1F3',
    grayButtonText: '#556070',
    shadowColor: '#0E1726',
  },
  radii: {
    card: 24,
    tag: 16,
    pill: 30,
    avatar: 999,
  },
  shadows: {
    card: {
      shadowColor: '#0E1726',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.07,
      shadowRadius: 14,
      elevation: 3,
    },
    cardHover: {
      shadowColor: '#0E1726',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 20,
      elevation: 6,
    },
    buttonOrange: {
      shadowColor: '#F57C2A',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.35,
      shadowRadius: 10,
      elevation: 4,
    },
    buttonTeal: {
      shadowColor: '#0E5B66',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 3,
    },
  },
};
